/* tslint:disable */
/* eslint-disable */
/**
 * Workspace API
 * Models that reference other models by $ref: an enum-valued property, a direct
object-valued property, an array whose items are a $ref, and a model that
references itself. Serializing these correctly requires following the
reference to import and call the referenced model's FromJSON/ToJSON helpers,
while a self-reference must not import its own declarations.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TreeNode
 */
export interface TreeNode {
    /**
     * 
     * @type {string}
     * @memberof TreeNode
     */
    id: string;
    /**
     * 
     * @type {TreeNode}
     * @memberof TreeNode
     */
    parent?: TreeNode;
    /**
     * 
     * @type {Array<TreeNode>}
     * @memberof TreeNode
     */
    children?: Array<TreeNode>;
}


/**
 * Check if a given object implements the TreeNode interface.
 */
export function instanceOfTreeNode(value: object): value is TreeNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TreeNodeFromJSON(json: any): TreeNode {
    return TreeNodeFromJSONTyped(json, false);
}

export function TreeNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parent': json['parent'] == null ? undefined : TreeNodeFromJSON(json['parent']),
        'children': json['children'] == null ? undefined : ((json['children'] as Array<any>).map(TreeNodeFromJSON)),
    };
}

export function TreeNodeToJSON(json: any): TreeNode {
    return TreeNodeToJSONTyped(json, false);
}

export function TreeNodeToJSONTyped(value?: TreeNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'parent': TreeNodeToJSON(value['parent']),
        'children': value['children'] == null ? undefined : ((value['children'] as Array<any>).map(TreeNodeToJSON)),
    };
}

