/* tslint:disable */
/* eslint-disable */
/**
 * Workspace API
 * Models that reference other models by $ref: an enum-valued property, a direct
object-valued property, and an array whose items are a $ref. Serializing these
correctly requires following the reference to import and call the referenced
model's FromJSON/ToJSON helpers.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WorkspaceStatus = {
    ACTIVE: "Active",
    SUSPENDED: "Suspended",
    ARCHIVED: "Archived"
} as const;
export type WorkspaceStatus = typeof WorkspaceStatus[keyof typeof WorkspaceStatus];

export function instanceOfWorkspaceStatus(value: any): boolean {
    for (const key in WorkspaceStatus) {
        if (Object.prototype.hasOwnProperty.call(WorkspaceStatus, key)) {
            if (WorkspaceStatus[key as keyof typeof WorkspaceStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkspaceStatusFromJSON(json: any): WorkspaceStatus {
    return WorkspaceStatusFromJSONTyped(json, false);
}

export function WorkspaceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceStatus {
    return json as WorkspaceStatus;
}

export function WorkspaceStatusToJSON(value?: WorkspaceStatus | null): any {
    return value as any;
}

export function WorkspaceStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkspaceStatus {
    return value as WorkspaceStatus;
}

