/* tslint:disable */
/* eslint-disable */
/**
 * Workspace API
 * Models that reference other models by $ref: an enum-valued property, a direct
object-valued property, an array whose items are a $ref, and a model that
references itself. Serializing these correctly requires following the
reference to import and call the referenced model's FromJSON/ToJSON helpers,
while a self-reference must not import its own declarations.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceStatus } from './WorkspaceStatus';
import {
    WorkspaceStatusFromJSON,
    WorkspaceStatusFromJSONTyped,
    WorkspaceStatusToJSON,
    WorkspaceStatusToJSONTyped,
} from './WorkspaceStatus';

/**
 * 
 * @export
 * @interface Workspace
 */
export interface Workspace {
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    id: string;
    /**
     * 
     * @type {WorkspaceStatus}
     * @memberof Workspace
     */
    status: WorkspaceStatus;
}


/**
 * Check if a given object implements the Workspace interface.
 */
export function instanceOfWorkspace(value: object): value is Workspace {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WorkspaceFromJSON(json: any): Workspace {
    return WorkspaceFromJSONTyped(json, false);
}

export function WorkspaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workspace {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': WorkspaceStatusFromJSON(json['status']),
    };
}

export function WorkspaceToJSON(json: any): Workspace {
    return WorkspaceToJSONTyped(json, false);
}

export function WorkspaceToJSONTyped(value?: Workspace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': WorkspaceStatusToJSON(value['status']),
    };
}

