/* tslint:disable */
/* eslint-disable */
/**
 * Workspace API
 * Models that reference other models by $ref: an enum-valued property, a direct
object-valued property, an array whose items are a $ref, and a model that
references itself. Serializing these correctly requires following the
reference to import and call the referenced model's FromJSON/ToJSON helpers,
while a self-reference must not import its own declarations.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Workspace } from './Workspace';
import {
    WorkspaceFromJSON,
    WorkspaceFromJSONTyped,
    WorkspaceToJSON,
    WorkspaceToJSONTyped,
} from './Workspace';

/**
 * 
 * @export
 * @interface WorkspaceListResponse
 */
export interface WorkspaceListResponse {
    /**
     * 
     * @type {Array<Workspace>}
     * @memberof WorkspaceListResponse
     */
    items: Array<Workspace>;
    /**
     * 
     * @type {Workspace}
     * @memberof WorkspaceListResponse
     */
    primary?: Workspace;
}


/**
 * Check if a given object implements the WorkspaceListResponse interface.
 */
export function instanceOfWorkspaceListResponse(value: object): value is WorkspaceListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WorkspaceListResponseFromJSON(json: any): WorkspaceListResponse {
    return WorkspaceListResponseFromJSONTyped(json, false);
}

export function WorkspaceListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WorkspaceFromJSON)),
        'primary': json['primary'] == null ? undefined : WorkspaceFromJSON(json['primary']),
    };
}

export function WorkspaceListResponseToJSON(json: any): WorkspaceListResponse {
    return WorkspaceListResponseToJSONTyped(json, false);
}

export function WorkspaceListResponseToJSONTyped(value?: WorkspaceListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WorkspaceToJSON)),
        'primary': WorkspaceToJSON(value['primary']),
    };
}

