/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Pet,
} from '../models/index';
import {
    PetFromJSON,
    PetToJSON,
} from '../models/index';

export interface CreatePetsRequest {
    pet: Pet;
}

export interface ListPetsRequest {
    limit?: number;
}

export interface ShowPetByIdRequest {
    petId: string;
}

/**
 * 
 */
export class PetsApi extends runtime.BaseAPI {

    /**
     * Create a pet
     */
    async createPetsRaw(requestParameters: CreatePetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pet'] == null) {
            throw new runtime.RequiredError(
                'pet',
                'Required parameter "pet" was null or undefined when calling createPets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pets`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PetToJSON(requestParameters['pet']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a pet
     */
    async createPets(requestParameters: CreatePetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPetsRaw(requestParameters, initOverrides);
    }

    /**
     * List all pets
     */
    async listPetsRaw(requestParameters: ListPetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Pet>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PetFromJSON));
    }

    /**
     * List all pets
     */
    async listPets(requestParameters: ListPetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Pet>> {
        const response = await this.listPetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Info for a specific pet
     */
    async showPetByIdRaw(requestParameters: ShowPetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pet>> {
        if (requestParameters['petId'] == null) {
            throw new runtime.RequiredError(
                'petId',
                'Required parameter "petId" was null or undefined when calling showPetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pets/{petId}`;
        urlPath = urlPath.replace(`{${"petId"}}`, encodeURIComponent(String(requestParameters['petId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PetFromJSON(jsonValue));
    }

    /**
     * Info for a specific pet
     */
    async showPetById(requestParameters: ShowPetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pet> {
        const response = await this.showPetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
