/* tslint:disable */
/* eslint-disable */
/**
 * Attribute Value API
 * A discriminated oneOf union whose variants carry a mix of Date and non-Date
payloads. Serializing it correctly requires dispatching on the discriminator,
so this sample covers union and date code generation.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CodeValue } from './CodeValue';
import {
    instanceOfCodeValue,
    CodeValueFromJSON,
    CodeValueFromJSONTyped,
    CodeValueToJSON,
} from './CodeValue';
import type { NumberValue } from './NumberValue';
import {
    instanceOfNumberValue,
    NumberValueFromJSON,
    NumberValueFromJSONTyped,
    NumberValueToJSON,
} from './NumberValue';
import type { NumberRangeValue } from './NumberRangeValue';
import {
    instanceOfNumberRangeValue,
    NumberRangeValueFromJSON,
    NumberRangeValueFromJSONTyped,
    NumberRangeValueToJSON,
} from './NumberRangeValue';
import type { DateValue } from './DateValue';
import {
    instanceOfDateValue,
    DateValueFromJSON,
    DateValueFromJSONTyped,
    DateValueToJSON,
} from './DateValue';
import type { DateRangeValue } from './DateRangeValue';
import {
    instanceOfDateRangeValue,
    DateRangeValueFromJSON,
    DateRangeValueFromJSONTyped,
    DateRangeValueToJSON,
} from './DateRangeValue';

/**
 * @type AttributeValue
 * 
 * @export
 */
export type AttributeValue = { valueKind: 'Code' } & CodeValue | { valueKind: 'Number' } & NumberValue | { valueKind: 'NumberRange' } & NumberRangeValue | { valueKind: 'Date' } & DateValue | { valueKind: 'DateRange' } & DateRangeValue;


export function AttributeValueFromJSON(json: any): AttributeValue {
    return AttributeValueFromJSONTyped(json, false);
}

export function AttributeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeValue {
    if (json == null) {
        return json;
    }
    switch (json['valueKind']) {
        case 'Code':
            return Object.assign({}, CodeValueFromJSONTyped(json, true), { valueKind: 'Code' } as const);
        case 'Number':
            return Object.assign({}, NumberValueFromJSONTyped(json, true), { valueKind: 'Number' } as const);
        case 'NumberRange':
            return Object.assign({}, NumberRangeValueFromJSONTyped(json, true), { valueKind: 'NumberRange' } as const);
        case 'Date':
            return Object.assign({}, DateValueFromJSONTyped(json, true), { valueKind: 'Date' } as const);
        case 'DateRange':
            return Object.assign({}, DateRangeValueFromJSONTyped(json, true), { valueKind: 'DateRange' } as const);
        default:
            return json;
    }
}

export function AttributeValueToJSON(json: any): any {
    return AttributeValueToJSONTyped(json, false);
}

export function AttributeValueToJSONTyped(value?: AttributeValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['valueKind']) {
        case 'Code':
            return Object.assign({}, CodeValueToJSON(value), { valueKind: 'Code' } as const);
        case 'Number':
            return Object.assign({}, NumberValueToJSON(value), { valueKind: 'Number' } as const);
        case 'NumberRange':
            return Object.assign({}, NumberRangeValueToJSON(value), { valueKind: 'NumberRange' } as const);
        case 'Date':
            return Object.assign({}, DateValueToJSON(value), { valueKind: 'Date' } as const);
        case 'DateRange':
            return Object.assign({}, DateRangeValueToJSON(value), { valueKind: 'DateRange' } as const);
        default:
            return value;
    }
}

