/* tslint:disable */
/* eslint-disable */
/**
 * Attribute Value API
 * A discriminated oneOf union whose variants carry a mix of Date and non-Date
payloads. Serializing it correctly requires dispatching on the discriminator,
so this sample covers union and date code generation.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeValue } from './AttributeValue';
import {
    AttributeValueFromJSON,
    AttributeValueFromJSONTyped,
    AttributeValueToJSON,
    AttributeValueToJSONTyped,
} from './AttributeValue';

/**
 * 
 * @export
 * @interface Attribute
 */
export interface Attribute {
    /**
     * 
     * @type {string}
     * @memberof Attribute
     */
    name: string;
    /**
     * 
     * @type {AttributeValue}
     * @memberof Attribute
     */
    value: AttributeValue;
    /**
     * 
     * @type {Date}
     * @memberof Attribute
     */
    effectiveOn?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Attribute
     */
    recordedAt: Date;
}


/**
 * Check if a given object implements the Attribute interface.
 */
export function instanceOfAttribute(value: object): value is Attribute {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('recordedAt' in value) || value['recordedAt'] === undefined) return false;
    return true;
}

export function AttributeFromJSON(json: any): Attribute {
    return AttributeFromJSONTyped(json, false);
}

export function AttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attribute {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': AttributeValueFromJSON(json['value']),
        'effectiveOn': json['effectiveOn'] == null ? undefined : (new Date(json['effectiveOn'])),
        'recordedAt': (new Date(json['recordedAt'])),
    };
}

export function AttributeToJSON(json: any): Attribute {
    return AttributeToJSONTyped(json, false);
}

export function AttributeToJSONTyped(value?: Attribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': AttributeValueToJSON(value['value']),
        'effectiveOn': value['effectiveOn'] == null ? value['effectiveOn'] : value['effectiveOn'].toISOString().substring(0,10),
        'recordedAt': value['recordedAt'].toISOString(),
    };
}

