/* tslint:disable */
/* eslint-disable */
/**
 * Attribute Value API
 * A discriminated oneOf union whose variants carry a mix of Date and non-Date
payloads. Serializing it correctly requires dispatching on the discriminator,
so this sample covers union and date code generation.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CodeValue
 */
export interface CodeValue {
    /**
     * 
     * @type {string}
     * @memberof CodeValue
     */
    valueKind: CodeValueValueKindEnum;
    /**
     * 
     * @type {string}
     * @memberof CodeValue
     */
    value: string;
}


/**
 * @export
 */
export const CodeValueValueKindEnum = {
    CODE: "Code"
} as const;
export type CodeValueValueKindEnum = typeof CodeValueValueKindEnum[keyof typeof CodeValueValueKindEnum];



/**
 * Check if a given object implements the CodeValue interface.
 */
export function instanceOfCodeValue(value: object): value is CodeValue {
    if (!('valueKind' in value) || value['valueKind'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CodeValueFromJSON(json: any): CodeValue {
    return CodeValueFromJSONTyped(json, false);
}

export function CodeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeValue {
    if (json == null) {
        return json;
    }
    return {
        
        'valueKind': json['valueKind'],
        'value': json['value'],
    };
}

export function CodeValueToJSON(json: any): CodeValue {
    return CodeValueToJSONTyped(json, false);
}

export function CodeValueToJSONTyped(value?: CodeValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valueKind': value['valueKind'],
        'value': value['value'],
    };
}

