/* tslint:disable */
/* eslint-disable */
/**
 * Attribute Value API
 * A discriminated oneOf union whose variants carry a mix of Date and non-Date
payloads. Serializing it correctly requires dispatching on the discriminator,
so this sample covers union and date code generation.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateRangeValue
 */
export interface DateRangeValue {
    /**
     * 
     * @type {string}
     * @memberof DateRangeValue
     */
    valueKind: DateRangeValueValueKindEnum;
    /**
     * 
     * @type {Date}
     * @memberof DateRangeValue
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof DateRangeValue
     */
    end: Date;
}


/**
 * @export
 */
export const DateRangeValueValueKindEnum = {
    DATERANGE: "DateRange"
} as const;
export type DateRangeValueValueKindEnum = typeof DateRangeValueValueKindEnum[keyof typeof DateRangeValueValueKindEnum];



/**
 * Check if a given object implements the DateRangeValue interface.
 */
export function instanceOfDateRangeValue(value: object): value is DateRangeValue {
    if (!('valueKind' in value) || value['valueKind'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function DateRangeValueFromJSON(json: any): DateRangeValue {
    return DateRangeValueFromJSONTyped(json, false);
}

export function DateRangeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateRangeValue {
    if (json == null) {
        return json;
    }
    return {
        
        'valueKind': json['valueKind'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
    };
}

export function DateRangeValueToJSON(json: any): DateRangeValue {
    return DateRangeValueToJSONTyped(json, false);
}

export function DateRangeValueToJSONTyped(value?: DateRangeValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valueKind': value['valueKind'],
        'start': value['start'].toISOString(),
        'end': value['end'].toISOString(),
    };
}

