/* tslint:disable */
/* eslint-disable */
/**
 * Attribute Value API
 * A discriminated oneOf union whose variants carry a mix of Date and non-Date
payloads. Serializing it correctly requires dispatching on the discriminator,
so this sample covers union and date code generation.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateValue
 */
export interface DateValue {
    /**
     * 
     * @type {string}
     * @memberof DateValue
     */
    valueKind: DateValueValueKindEnum;
    /**
     * 
     * @type {Date}
     * @memberof DateValue
     */
    value: Date;
}


/**
 * @export
 */
export const DateValueValueKindEnum = {
    DATE: "Date"
} as const;
export type DateValueValueKindEnum = typeof DateValueValueKindEnum[keyof typeof DateValueValueKindEnum];



/**
 * Check if a given object implements the DateValue interface.
 */
export function instanceOfDateValue(value: object): value is DateValue {
    if (!('valueKind' in value) || value['valueKind'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function DateValueFromJSON(json: any): DateValue {
    return DateValueFromJSONTyped(json, false);
}

export function DateValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateValue {
    if (json == null) {
        return json;
    }
    return {
        
        'valueKind': json['valueKind'],
        'value': (new Date(json['value'])),
    };
}

export function DateValueToJSON(json: any): DateValue {
    return DateValueToJSONTyped(json, false);
}

export function DateValueToJSONTyped(value?: DateValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valueKind': value['valueKind'],
        'value': value['value'].toISOString(),
    };
}

