/* tslint:disable */
/* eslint-disable */
/**
 * Attribute Value API
 * A discriminated oneOf union whose variants carry a mix of Date and non-Date
payloads. Serializing it correctly requires dispatching on the discriminator,
so this sample covers union and date code generation.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NumberValue
 */
export interface NumberValue {
    /**
     * 
     * @type {string}
     * @memberof NumberValue
     */
    valueKind: NumberValueValueKindEnum;
    /**
     * 
     * @type {number}
     * @memberof NumberValue
     */
    value: number;
}


/**
 * @export
 */
export const NumberValueValueKindEnum = {
    NUMBER: "Number"
} as const;
export type NumberValueValueKindEnum = typeof NumberValueValueKindEnum[keyof typeof NumberValueValueKindEnum];



/**
 * Check if a given object implements the NumberValue interface.
 */
export function instanceOfNumberValue(value: object): value is NumberValue {
    if (!('valueKind' in value) || value['valueKind'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function NumberValueFromJSON(json: any): NumberValue {
    return NumberValueFromJSONTyped(json, false);
}

export function NumberValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberValue {
    if (json == null) {
        return json;
    }
    return {
        
        'valueKind': json['valueKind'],
        'value': json['value'],
    };
}

export function NumberValueToJSON(json: any): NumberValue {
    return NumberValueToJSONTyped(json, false);
}

export function NumberValueToJSONTyped(value?: NumberValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valueKind': value['valueKind'],
        'value': value['value'],
    };
}

