/* tslint:disable */
/* eslint-disable */
/**
 * Attribute Value API
 * A discriminated oneOf union whose variants carry a mix of Date and non-Date
payloads. Serializing it correctly requires dispatching on the discriminator,
so this sample covers union and date code generation.

 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NumberRangeValue
 */
export interface NumberRangeValue {
    /**
     * 
     * @type {string}
     * @memberof NumberRangeValue
     */
    valueKind: NumberRangeValueValueKindEnum;
    /**
     * 
     * @type {number}
     * @memberof NumberRangeValue
     */
    start: number;
    /**
     * 
     * @type {number}
     * @memberof NumberRangeValue
     */
    end: number;
}


/**
 * @export
 */
export const NumberRangeValueValueKindEnum = {
    NUMBERRANGE: "NumberRange"
} as const;
export type NumberRangeValueValueKindEnum = typeof NumberRangeValueValueKindEnum[keyof typeof NumberRangeValueValueKindEnum];



/**
 * Check if a given object implements the NumberRangeValue interface.
 */
export function instanceOfNumberRangeValue(value: object): value is NumberRangeValue {
    if (!('valueKind' in value) || value['valueKind'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function NumberRangeValueFromJSON(json: any): NumberRangeValue {
    return NumberRangeValueFromJSONTyped(json, false);
}

export function NumberRangeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberRangeValue {
    if (json == null) {
        return json;
    }
    return {
        
        'valueKind': json['valueKind'],
        'start': json['start'],
        'end': json['end'],
    };
}

export function NumberRangeValueToJSON(json: any): NumberRangeValue {
    return NumberRangeValueToJSONTyped(json, false);
}

export function NumberRangeValueToJSONTyped(value?: NumberRangeValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valueKind': value['valueKind'],
        'start': value['start'],
        'end': value['end'],
    };
}

